#-------------------------------
# Site Settings

eng_name: Opensource Marketing
title: 오픈소스마케팅
tagline: 오소마 | 디지털 마케팅 전문 컨설팅 팀
logo: /images/logo/logo_980x518_no-bg_dark.png
description: 오소마는 파트너의 비즈니스 성장과 디지털 마케팅 최적화를 위한 방향성을 제안하며, 코칭 서비스를 제공하는 디지털 마케팅 전문 컨설팅 팀입니다.
thumbnail: /images/main_thumb.jpg

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Event'
      url: '/event/'
    - title: 'Ads'
      url: '/tag/ads'
    - title: 'GA'
      url: '/tag/ga'
    - title: 'Docs'
      url: 'https://docs.osoma.kr/'

# Call to action button
cta__button__text: 컨설팅 문의

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: 오픈소스마케팅
  title: 오픈소스마케팅
  bio: 오픈소스마케팅은 파트너의 비즈니스 성장과 디지털 마케팅 최적화를 위한 방향성을 제안하며, 코칭 서비스를 제공하는 디지털 마케팅 전문 컨설팅 팀입니다.
  image: '/images/01.jpg'
  avatar: '/images/avatar.jpg'
  button__text: 회사소개서 다운로드


#-------------------------------
# Projects Settings

projects__settings:
  projects__title:  # Add a 'text-span' class to highlight text.
  projects__description:


#-------------------------------
# Testimonials Section

testimonial__title:  # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: ""
    image: ""
    designation : ""
    content : ""

  - name: ""
    image: ""
    designation : ""
    content : ""

#-------------------------------
# Blog Section

blog__settings:
  blog__title: 최근 <span class="text-span">블로그</span> 글 # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: contact@osoma.kr # Add your email for contact form
  contact__title: <span class="text-span">문의</span> 남기기 # Add a title to your form
  contact__description: 오픈소스마케팅의 컨설팅이 필요하시다면 문의를 남겨주세요. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: 오소마 뉴스레터를<br>지금 <span class="text-span">구독하세요</span> # Add your title
  mailchimp__text: " '오픈소스마케팅의 최신 소식을', '가장 빠르게 받아보세요!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: osoma.us20.list-manage.com/subscribe/post?u=85d5c5fbf1124f4e577a13861&amp;id=3e12916440 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: 구독하기 # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {name: "페이스북", icon: "brandico:facebook-rect", link: "https://facebook.com/osoma.kr"}
- {name: "링크드인", icon: "brandico:linkedin-rect", link: "https://www.linkedin.com/company/opensourcemarketing"}
- {name: "카카오톡", icon: "vs:kakaotalk", link: "http://pf.kakao.com/_PLzxcj"}
- {name: "유튜브", icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UC0-tqcM8MkMIUM1nEr_0Vtw"}
